import type { Metadata } from "next";
import "./globals.css";
import TanstackProvider from "@/providers";
import { AuthProvider } from "@/providers/auth-provider";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="unselectable antialiased"
        suppressHydrationWarning={true}
      >
        <ReactQueryProvider>
          <TanstackProvider>
            <AuthProvider>
              {children}
              <Toaster position="top-center" reverseOrder={false} />
            </AuthProvider>
          </TanstackProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
